[build]
target = ["riscv64gc-unknown-linux-musl"]

[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-unknown-linux-musl-gcc"
ar = "riscv64-unknown-linux-musl-ar"

[unstable]
build-std = ["core", "std", "alloc", "proc_macro", "test"]
